---
wireguard_config_dir: /root/.config/chameleon

wireguard_default_tunnels:
  mgmt:
    # TODO: support other than /24
    ipv4: "{{ mgmt_ipv4 }}/24"
    routes:
      - 10.20.110.0/23 via 10.0.0.2
    peers:
      - public_key: 88w0zYhwnVxq9BXNwrinYRpEqmrNujCFdWigTf/MTXE=
        endpoint: 129.114.34.129:51820
        keepalive: True
        allowed_ips:
          - 10.0.0.2/32
          - 10.20.111.10/32
          - 10.20.111.11/32
  user:
    # TODO: support other than /24
    ipv4: "{{ user_ipv4 }}/24"
    peers:
      - public_key: Vc8OzWeU3uSZgUs7xw1uG55r3YmvHxQnyPwOwq5dfQM=
        endpoint: 129.114.34.129:57513
        keepalive: True
        allowed_ips:
          - 10.0.1.0/24
wireguard_extra_tunnels: {}

wireguard_tunnels: "{{ wireguard_default_tunnels | combine(wireguard_extra_tunnels) }}"
