---
- name: store wg0 public key
  command: wg show wg0 public-key
  register: wg0_pubkey
  changed_when: false

- name: store wg1 public key
  command: wg show wg1 public-key
  register: wg1_pubkey
  changed_when: false

- name: print command for mgmt interface
  debug:
    msg: wg set wg0 peer {{ wg0_pubkey.stdout }} allowed-ips {{ mgmt_ipv4 }}

- name: print command for user interface
  debug:
    msg: wg set wg1 peer {{ wg1_pubkey.stdout }} allowed-ips {{ user_ipv4 }}
