---
- name: check if module backup exists
  ansible.builtin.stat:
    path: /lib/modules/4.9.201-tegra.backup
  register: backup

- name: backup kernel modules
  ansible.builtin.command: mv /lib/modules/4.9.201-tegra/ /lib/modules/4.9.201-tegra.backup/
  when: backup.stat.exists == false

- name: download kernel supplements
  ansible.builtin.unarchive:
    src: https://github.com/ChameleonCloud/kernel-jetson-nano/releases/download/0.3/kernel_supplements.tbz2
    dest: /
    remote_src: True

- name: check if boot image backup exists
  ansible.builtin.stat:
    path: /boot/Image.backup
  register: boot_image_backup

- name: backup boot image
  ansible.builtin.command: mv /boot/Image /boot/Image.backup
  when: boot_image_backup.stat.exists == false

- name: download boot image
  ansible.builtin.get_url:
    url: https://github.com/ChameleonCloud/kernel-jetson-nano/releases/download/0.3/Image
    dest: /boot/Image
