---
- import_tasks: ovs.yml

- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  with_dict: "{{ neutron_services }}"

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over neutron.conf
  become: true
  vars:
    service_name: "{{ item.key }}"
    services_need_neutron_conf:
      - "neutron-openvswitch-agent"
  template:
    src: "{{ role_path }}/templates/neutron.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/neutron.conf"
    mode: "0660"
  when:
    - item.key in services_need_neutron_conf
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over openvswitch_agent.ini
  become: true
  vars:
    service_name: "neutron-openvswitch-agent"
  template:
    src: "{{ role_path }}/templates/openvswitch_agent.ini.j2"
    dest: "{{ node_config_directory }}/{{ service_name }}/openvswitch_agent.ini"
    mode: "0660"
  notify:
    - "Restart {{ service_name }} container"

- name: Check neutron containers
  become: true
  kolla_docker:
    action: "compare_container"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"
