---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_dict: "{{ zun_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  with_dict: "{{ zun_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over zun.conf
  vars:
    service_name: "{{ item.key }}"
  template:
    src: "{{ role_path }}/templates/zun.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/zun.conf"
    mode: "0660"
  become: true
  with_dict: "{{ zun_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Check zun containers
  become: true
  kolla_docker:
    action: "compare_container"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
    healthcheck: "{{ item.value.healthcheck | default(omit) }}"
  with_dict: "{{ zun_services }}"
  notify:
    - "Restart {{ item.key }} container"
